[package]
name = "simple_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
scraper = "0.19"
tokio = { version = "1.47.0", features = ["full"] }
futures = "0.3"